apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: northstar-web
  namespace: northstar
spec:
  minAvailable: 80%
  selector:
    matchLabels:
      app.kubernetes.io/name: northstar-web
