apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: northstar-runtime
  namespace: northstar
spec:
  provider: azure
  secretObjects:
    - secretName: northstar-runtime
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: JWT_SECRET
          key: JWT_SECRET
        - objectName: ORIGIN_VERIFY_TOKEN
          key: ORIGIN_VERIFY_TOKEN
        - objectName: APPLICATIONINSIGHTS_CONNECTION_STRING
          key: APPLICATIONINSIGHTS_CONNECTION_STRING
  parameters:
    usePodIdentity: "false"
    clientID: "${WORKLOAD_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    tenantId: "${AZURE_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: northstar-database-url
          objectAlias: DATABASE_URL
          objectType: secret
        - |
          objectName: northstar-jwt-secret
          objectAlias: JWT_SECRET
          objectType: secret
        - |
          objectName: northstar-origin-token
          objectAlias: ORIGIN_VERIFY_TOKEN
          objectType: secret
        - |
          objectName: northstar-app-insights-connection-string
          objectAlias: APPLICATIONINSIGHTS_CONNECTION_STRING
          objectType: secret
